INSERT INTO tb_news (title, date_created, content, author, tags) VALUES ('Lorem ipsum dolor', TIMESTAMP WITH TIME ZONE '2022-01-01T00:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed laoreet lorem. Morbi iaculis turpis id dolor placerat dapibus. Praesent non mauris lobortis, mattis nulla ac, pellentesque mi. Vivamus ac turpis eleifend justo consectetur porttitor. Mauris imperdiet suscipit mattis. Ut sed odio a tellus dictum posuere in vel neque. Curabitur et volutpat eros. Nam rhoncus cursus metus quis facilisis. Vestibulum id iaculis odio, id mollis lectus.', 'João da Silva', '#technology #interesting');

INSERT INTO tb_comment (content, date_created, author, news) VALUES ('In fringilla sapien ut metus finibus varius. Praesent non mauris lobortis, mattis nulla ac, pellentesque mi. Vivamus ac turpis eleifend justo consectetur porttitor. Mauris imperdiet suscipit mattis. Ut sed odio a tellus dictum posuere in vel neque. Curabitur et volutpat eros. Nam rhoncus cursus metus quis facilisis. Vestibulum id iaculis odio, id mollis lectus.', TIMESTAMP WITH TIME ZONE '2022-01-01T00:00:00Z', 'Maria da Silva', 1);
INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Donec ac eros lacus. Ut feugiat, leo et vestibulum condimentum, magna lorem ultricies velit, sit amet viverra mi nisi at ante.', TIMESTAMP WITH TIME ZONE '2022-01-05T00:00:00Z', 'Carlos da Silva', 1);

INSERT INTO tb_news (title, date_created, content, author, tags) VALUES ('Aliquam erat volutpat', TIMESTAMP WITH TIME ZONE '2022-01-10T00:00:00Z', 'Pellentesque quis ullamcorper nulla, nec faucibus lacus. Vestibulum efficitur suscipit erat, quis tincidunt nulla placerat id. Mauris nec iaculis purus, ac scelerisque risus. Aliquam erat volutpat. Donec consequat elementum odio ullamcorper fermentum. Curabitur vulputate id risus at tincidunt. Proin sed tristique diam. Fusce dolor lorem, tincidunt ut sagittis a, posuere non tellus. Nunc urna ligula, eleifend vel tincidunt in, venenatis sed erat.', 'Fernanda Morais', '#java #angular');

INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Curabitur pellentesque eleifend purus.', TIMESTAMP WITH TIME ZONE '2022-01-11T00:00:00Z', 'Eduardo Ribeiro', 2);
INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Quisque facilisis, libero sed finibus ultricies, augue justo aliquet tortor, a tincidunt sapien nulla vel ante.', TIMESTAMP WITH TIME ZONE '2022-01-12T00:00:00Z', 'Anderson dos Santos', 2);

INSERT INTO tb_news (title, date_created, content, author, tags) VALUES ('Proin eros magna', TIMESTAMP WITH TIME ZONE '2022-01-15T00:00:00Z', 'Proin eros magna, mattis in urna in, vulputate dignissim massa. In vitae felis ipsum. Mauris dignissim rhoncus orci, malesuada interdum eros. Etiam ullamcorper in nibh sed pharetra. Quisque maximus blandit finibus. Praesent non nulla sapien. Morbi vel porta arcu, sit amet hendrerit purus.', 'Júlia Souza', '#css #bootstrap #webdesigner');

INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Suspendisse dapibus orci at turpis varius finibus.', TIMESTAMP WITH TIME ZONE '2022-01-15T00:00:00Z', 'Mônica Lima', 3);
INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Ut arcu tellus, sodales et orci a, efficitur tincidunt arcu.', TIMESTAMP WITH TIME ZONE '2022-01-12T00:00:00Z', 'Alberto Ribeiro', 3);
INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Morbi vel porta arcu, sit amet hendrerit purus.', TIMESTAMP WITH TIME ZONE '2022-01-17T00:00:00Z', 'José Fernandes', 3);

INSERT INTO tb_news (title, date_created, content, author, tags) VALUES ('Aliquam ligula ante', TIMESTAMP WITH TIME ZONE '2022-01-17T00:00:00Z', 'Cras suscipit velit vel metus accumsan ornare. Pellentesque tristique est a ex gravida maximus. Integer at enim vel mauris venenatis tempor mollis at massa. Integer dictum finibus dignissim. Aenean dapibus ultrices neque ac finibus. Vestibulum suscipit purus nisl. Praesent iaculis leo libero, vitae ullamcorper nisl volutpat consequat. Nullam auctor vehicula convallis. In fringilla sapien ut metus finibus varius.', 'João Roberto', '#apirest #spring #java17');

INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Sed commodo tellus eu varius laoreet.', TIMESTAMP WITH TIME ZONE '2022-01-15T00:00:00Z', 'Mateus Martins', 4);

INSERT INTO tb_news (title, date_created, content, author, tags) VALUES ('Curabitur ac mi dui.', TIMESTAMP WITH TIME ZONE '2022-01-18T00:00:00Z', 'Vivamus pretium non odio vel laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac porta lectus. Integer et accumsan felis. Fusce eu accumsan orci, eu sollicitudin nisi. Donec pretium iaculis tortor, id cursus eros tempor ac. Ut sagittis posuere elit vitae rhoncus.', 'João da Silva', '#database #mysql #postgresql #security');

INSERT INTO tb_comment (content, date_created, author, news) VALUES ('Integer laoreet nibh porta metus sagittis, eget ultrices libero maximus.', TIMESTAMP WITH TIME ZONE '2022-01-19T00:00:00Z', 'Jorge Souza', 5);

INSERT INTO tb_news (title, date_created, content, author, tags) VALUES ('Fusce eu accumsan orci.', TIMESTAMP WITH TIME ZONE '2022-02-05T00:00:00Z', 'Vivamus pretium non odio vel laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac porta lectus. Integer et accumsan felis. Fusce eu accumsan orci, eu sollicitudin nisi. Donec pretium iaculis tortor, id cursus eros tempor ac. Ut sagittis posuere elit vitae rhoncus. Morbi ullamcorper enim a est accumsan hendrerit. Donec non pretium nisl. Ut lobortis risus at hendrerit congue.', 'Júlia Souza', '#react #reactnative #bootstrap');